exclude = [
    ".venv",
    "**/*.egg-info",
    "__pycache__",
    "**/*.ipynb",
    ".git",
    "build",
]

[lint]
select = ["E", "F", "W"]
ignore = [
    "E501",
    "E402",
    "W291",
    "W293",
]